### ISSUE TITLE
Will this support "Scan-to-WSD"?

### ISSUE THREAD

**Issue by bllngr** [alexpevzner/sane-airscan-unstable#3]
My MFP supports something called "Scan to WSD", which basically triggers a scan process from the device. This is very handy, since you can setup the driver in a way that documents can be scanned with predefined settings to a document with just a single key press.

However, this only works on Windows with the proprietary driver. Is there any chance I could use this project to get the same feature to a Linux host?

**Comment by alexpevzner** [comment]
This project will support WSD scanning, triggered from computer.

To support wSD scanning, triggered from device, the very different software architecture is required. There must be a process, running at host and waiting to catch scanned documents, WS-Discovery responder at the host side, appropriate firewall configuration and so on. This all is out of scope of this project.

So short answer is "no".

BTW, I wonder, most of devices, able to scan to WSD, also able to scan to e-mail or ftp. From the user experience perspective all these variants looks similar. Why not to use scan to e-mail or ftp?
