### ISSUE TITLE
Error when ADF runs empty

### ISSUE THREAD

**Issue by dwagenk** [alexpevzner/sane-airscan-unstable#9]
Not sure, if this is the right spot to report this, since I've read some of the discussion in [issue 202](https://gitlab.com/sane-project/backends/-/issues/202) and it sounded like this project should move.

I noticed one problem with the `airscan` backend that the `escl` backend doesn't have:
- when the ADF runs empty after scanning one or more pages `airscan` reports `Error during device I/O`

I think [this](https://gitlab.com/sane-project/backends/-/merge_requests/433) shows the handling that's needed to fix this problem.

**Comment by alexpevzner** [comment]
Hi @DWagenk,

different scanners report BUSY/NO_DOSC status the different way, so I need to be careful touching this to avoid breaking of other devices.

May I ask you to gather protocol trace, when error is reproduced?

To do so, you will need to uncomment the following lines in `/etc/sane.d/airscan.conf`:

    [debug]
    trace = ~/airscan/trace
    enable = true

Logs will placed into the `~/airscan/trace` directory, which will be created automatically. Generated `.tar` files are not needed, for this issue I need only `.log` files.

You may send me them directly to pzz@apevzner.com

Thank in advance!

**Comment by dwagenk** [comment]
This seems to be the interesting one, mentioning the error in lines 248, 251, 266. I scanned two A4 sheets of paper using simple-scan. [perl-Canon-TR4500-series.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4671612/perl-Canon-TR4500-series.log)

other logs:
[perl-canon.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4671611/perl-canon.log)
[scanimage-canon.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4671613/scanimage-canon.log)
[scanimage-Canon-TR4500-series.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4671614/scanimage-Canon-TR4500-series.log)
[xsane-canon.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4671615/xsane-canon.log)
[xsane-Canon-TR4500-series.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4671616/xsane-Canon-TR4500-series.log)

**Comment by alexpevzner** [comment]
Seems you are using old version of sane-airscan. Please, upgrade to the latest version and retest. Please, use the "stable" branch: https://github.com/alexpevzner/sane-airscan

**Comment by dwagenk** [comment]
Hi, sorry, didn't notice the new releases beforehand.

The problem persists with 0.99.2 though.
[simple-scan-wrapped-Canon-TR4500-series.log](https://github.com/alexpevzner/sane-airscan-wsd/files/4673458/simple-scan-wrapped-Canon-TR4500-series.log)

**Comment by alexpevzner** [comment]
Hi @DWagenk,

I've tried to fix this bug. May I ask you to build driver by yourself and retest, before I'll issue a new release?

**Comment by dwagenk** [comment]
@alexpevzner I'll do that. Might take two or three days until I get to it though.

**Comment by alexpevzner** [comment]
OK, I've build by myself. Please, try the 0.99.3 release

**Comment by dwagenk** [comment]
@alexpevzner tested with 0.99.3 (https://github.com/alexpevzner/sane-airscan/commit/43e5a0e12f080a689fa143e6ba459b47f483ce1d) and it works as expected now. Thanks!

**Comment by alexpevzner** [comment]
Thank you for your feedback!
